version: "3.5"

networks:
  default-network:
    external: false

volumes:
  psql-volume:

services:
  nginx:
    image: nginx:1.19-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/app/frontend/build
    networks:
      - default-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: artsai_backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/:/app/backend
    links:
      - psql
      - redis
    networks:
      - default-network

  psql:
    env_file:
      - ./backend/.env
    image: postgres:12.5
    container_name: artsai_psql
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - psql-volume:/var/lib/db/data
    ports:
      - 5432:5432
    networks:
      - default-network

  redis:
    image: redis:alpine
    container_name: artsai_redis
    ports:
      - 6379:6379
    networks:
      - default-network
